version: "3"
volumes:
        bundle: { driver: local }
        node_modules: { driver: local }
        config: { driver: local }
services:
        app:
                image: alpinelab/ruby-dev
                ports: ["5000:5000"]
                volumes:
                        - .:/app
                        - bundle:/bundle
                        - node_modules:/app/node_modules
                        - config:/config
